### ISSUE TITLE
Path Tools uncontrolled acceleration for follower

### ISSUE THREAD

**Issue by franksharpsword** [romifauzi/PathTools#1]
The number of red lines between two points should not remain constant. The length of the curve between two points should be calculated and the number of red lines should be increased or decreased accordingly. Because when the intensity of the red lines decreases, the speed of the follower increases. If this is corrected, it would be awesome. Please let me know when it's fixed. Thank you.

**Comment by romifauzi** [comment]
Hi Frank, thank you so much for reporting this, I apologize it took very long for me to response. I'm currently looking into this.

**Comment by romifauzi** [comment]
This is fixed in commit: https://github.com/romifauzi/PathTools/commit/66345263b8c60e57dba1602787e845818b244ce5 , closing this now. Thanks
